reg-viz/reg-cli

report/src/app.vue
I found `chaged` and fix it to `changed`.
Also I found it at report/dist/build.js but I don't know how to update this file...
=> Fix typo :police_car:

src/index.js, yarn.lock
calculate percentage for image-difference
=> Fix threshold

src/index.js
=> Fix filtering results of promises

.circleci/config.yml, package.json, test/cli.test.js, yarn.lock
=> Use circleci

.circleci/config.yml, package.json
=> Use avaron on circleci

src/index.js
=> Add `disableUpdateMessage` option

decls/cross-spawn.js, package.json, src/diff.js, src/index.js, src/report.js, test/cli.test.js, yarn.lock
improve diff perf
- Execute diff creator on multi process using cross-spawn.
=> Improve diff perf

.circleci/config.yml
=> fix circleCI build step

package.json, report/src/views/ComparisonModal.vue, yarn.lock
Draw bounding rectangles for each matching region
=> Render bounding

src/index.js
related #124 
Fixed a bug, some error occurred when update images with `-U` flag.
=> fix: Fix expected dir cleanup

README.md, src/cli.js, test/cli.test.js
=> added possibility to exit with error on image addition or deletions

src/cli.js
=> added missing definition for extendedErrors param

package.json
Added some styling and behavior fixes: dog:
=> feat: Report UI v0.0.3

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
I added Issue and Pull Request templates.
We expect users to contribute in a unified format :memo:
=> docs: Add GitHub Issue & Pull Request templates

package.json
I fixed bugs related to the sidebar... :bow:
https://github.com/reg-viz/reg-cli-report-ui/pull/21
=> feat: Report UI v0.0.4

package.json
See https://github.com/reg-viz/reg-cli-report-ui/pull/23
- https://github.com/reg-viz/reg-cli-report-ui/pull/23
:dog: :camera:
- Encoded file names are used.
=> feat: Report UI v0.0.5

package.json
- Marker style (https://github.com/reg-viz/reg-cli-report-ui/pull/25)
- Fixed a bug where the diff items path was inconsistent when using jpg files (https://github.com/reg-viz/reg-cli-report-ui/pull/26)
:dog2: :dash:
- If you have links to other resources, please list them here. (e.g. issue url, related pull request url, documents)
If applicable, add screenshots to help explain your changes.
Please briefly describe how you can confirm the resolution of the bug.
=> feat: Report UI v0.1.1

package.json
- Multiline card title (https://github.com/reg-viz/reg-cli-report-ui/pull/30)
:dog2: :dash:
- https://github.com/reg-viz/reg-cli-report-ui/pull/30
Nothing.
Nothing.
=> feat: Report UI v0.1.2

package.json
- Fix broken image file when using `urlPrefix` flag (https://github.com/reg-viz/reg-cli-report-ui/pull/32)
:dog2: :dash:
- https://github.com/reg-viz/reg-cli-report-ui/pull/32
- Nothing.
- Nothing.
=> feat: Report UI v0.1.3

package.json
:dog2: :dash:
- Update fuzzy search behavior
- Add markers toggle
- Switch to preact from react
- Improve behavior for iOS Safari
- Add entity permalink
- Use `:focus-visible` instead of `:focus`
- Add keymap for `<ChoiceGroup />` component
- Disable smooth-scroll
- Change image comparison to a top-aligned design
- Update dependencies & devDependencies
- https://github.com/reg-viz/reg-cli-report-ui/pull/44
- https://github.com/reg-viz/reg-cli-report-ui/pull/43
- https://github.com/reg-viz/reg-cli-report-ui/pull/42
- https://github.com/reg-viz/reg-cli-report-ui/pull/41
- https://github.com/reg-viz/reg-cli-report-ui/pull/40
- https://github.com/reg-viz/reg-cli-report-ui/pull/39
- https://github.com/reg-viz/reg-cli-report-ui/pull/38
- https://github.com/reg-viz/reg-cli-report-ui/pull/37
- …
=> feat: Report UI v0.2.0

package.json
Related #405
https://github.com/reg-viz/reg-cli-report-ui/compare/v0.2.0...v0.2.1
- https://github.com/reg-viz/reg-cli-report-ui/pull/48
- https://github.com/reg-viz/reg-cli-report-ui/pull/46
n/a
n/a
=> feat: Report UI v0.2.1

src/cli.js, test/cli.test.js
resolve #425 
adds support for a custom diff message
#425
=> feat: adds support for a custom diff message

.github/workflows/ci.yml, package.json, src/index.js, src/report.js, test/screenshot.js
close https://github.com/reg-viz/reg-cli/issues/480
- If you have links to other resources, please list them here. (e.g. issue url, related pull request url, documents)
If applicable, add screenshots to help explain your changes.
Please briefly describe how you can confirm the resolution of the bug.
=> fix: use make dir instead of mkdirp

package.json, sample/worker.js, src/report.js, template/template.html
- Related
- [#49](https://github.com/reg-viz/reg-cli-report-ui/pull/49)
- [#53](https://github.com/reg-viz/reg-cli-report-ui/pull/53)
- [#55](https://github.com/reg-viz/reg-cli-report-ui/pull/55)
- [#56](https://github.com/reg-viz/reg-cli-report-ui/pull/56)
- [#58](https://github.com/reg-viz/reg-cli-report-ui/pull/58)
- [#60](https://github.com/reg-viz/reg-cli-report-ui/pull/60)
- And updates some dependencies
https://github.com/reg-viz/reg-cli-report-ui/compare/v0.2.1...v0.3.0
- N/A
N/A
N/A
=> feat: Report UI v0.3.0

package.json
See:
https://github.com/reg-viz/reg-cli-report-ui/releases/tag/v0.4.0
- https://github.com/reg-viz/reg-cli-report-ui/pull/64
- https://github.com/reg-viz/reg-cli-report-ui/pull/65
n/a
n/a
=> feat: Report UI v0.4.0

CHANGELOG.md, package.json
A clear and concise description of what the changes is.
- If you have links to other resources, please list them here. (e.g. issue url, related pull request url, documents)
If applicable, add screenshots to help explain your changes.
Please briefly describe how you can confirm the resolution of the bug.
=> Publish 0.18.8

package.json
See:
https://github.com/reg-viz/reg-cli-report-ui/releases/tag/v0.5.0
- https://github.com/reg-viz/reg-cli-report-ui/pull/70
=> feat: Report UI v0.5.0
